services:
  cloud-labs:
    build:
      context: ./module-cloud-labs
      dockerfile: Dockerfile
    container_name: mfe-cloud-labs
    ports:
      - "3001:80"
    networks:
      - micro-net
    restart: unless-stopped

  dashboard:
    build:
      context: ./module-dashboard
      dockerfile: Dockerfile
    container_name: mfe-dashboard
    ports:
      - "3002:80"
    networks:
      - micro-net
    restart: unless-stopped

  virtual-machine:
    build:
      context: ./module-virtual-machine
      dockerfile: Dockerfile
    container_name: mfe-virtual-machine
    ports:
      - "3003:80"
    networks:
      - micro-net
    restart: unless-stopped

  shell:
    build:
      context: ./shell-app
      dockerfile: Dockerfile
    container_name: mfe-shell
    ports:
      - "3000:80"
    networks:
      - micro-net
    depends_on:
      - cloud-labs
      - dashboard
      - virtual-machine
    restart: unless-stopped

networks:
  micro-net:
    driver: bridge
    name: micro-frontend-network
